### ISSUE TITLE
Problem with Travertine.

### ISSUE THREAD

**Issue by QuickGlare** [WaterfallMC/Travertine#77] opened 2018-08-21 21:53 UTC
When a "player" (bot) try to join trought the proxy, it will give this error:
https://hastebin.com/yihikopeta.bash

Travertine Version: "This server is running Travertine version git:Travertine-Bootstrap:1.13-SNAPSHOT:1692703:61 by md_5"

We are not using plugins.

**Comment by electronicboy** [comment] 2018-08-21 21:54
Duplicate of https://github.com/WaterfallMC/Waterfall/issues/264

**Closed by electronicboy** 2018-08-21 21:54 UTC
